#!/bin/bash

if command -v shasum &> /dev/null;
then 
    SHA=$(which shasum)
elif command -v sha256sum &> /dev/null;
then
    SHA=$(which sha256sum)
else
    echo "No SHA utility!"
    exit
fi

if [ -n $1 ]; then
  KEY=$1
else
  KEY=$( cat /dev/urandom | base64 | head -c 20)
fi
PW=$(echo -n "${KEY}:$1" | $SHA | perl -ne "s/([0-9a-f]{2})/print chr hex \$1/gie" | base64 | tr +/ Ea | cut -b 1-20)
echo $PW
